<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app'
import { useCartStore } from '@/stores/cart'
import { request } from '@/utils/request'
import type { Address, Order } from '@/types'
const cart=useCartStore();onShow(()=>cart.load())
async function checkout(){if(!cart.items.length)return;const addresses=await request<Address[]>({url:'/user/addresses',method:'GET'});if(!addresses.length){uni.showToast({title:'请先添加地址',icon:'none'});return}const order=await request<Order>({url:'/user/orders',method:'POST',data:{clientOrderNo:`uni-${Date.now()}`,addressBookId:addresses[0].id,remark:''}});uni.showModal({title:'订单创建成功',content:`应付 ¥${order.amount}，是否模拟支付？`,success:async r=>{if(r.confirm){await request<void>({url:`/user/orders/${order.id}/mock-pay`,method:'POST'});uni.switchTab({url:'/pages/order/index'})}}})}
</script>
<template><view class="cart-page"><view class="heading"><text>购物车</text><text class="clear" @click="cart.clear">清空</text></view><view v-if="!cart.items.length" class="empty">购物车还是空的<text>去挑选喜欢的菜品吧</text></view><view v-for="item in cart.items" :key="item.id" class="item"><view class="thumb">膳</view><view class="item-main"><text class="name">{{item.dishName}}</text><text class="price">¥{{item.unitPrice}}</text></view><text>× {{item.quantity}}</text></view><view v-if="cart.items.length" class="settle"><view><text>合计</text><text class="total">¥{{cart.totalPrice.toFixed(2)}}</text></view><button @click="checkout">提交订单</button></view></view></template>
<style scoped lang="scss">.cart-page{padding:30rpx}.heading{display:flex;justify-content:space-between;font-size:38rpx;font-weight:700;margin:20rpx 0 30rpx}.clear{font-size:24rpx;font-weight:400;color:#888}.empty{text-align:center;color:#65716b;padding:180rpx 0}.empty text{display:block;font-size:24rpx;color:#a0a8a4;margin-top:16rpx}.item{display:flex;align-items:center;background:#fff;padding:24rpx;border-radius:24rpx;margin-bottom:18rpx}.thumb{width:110rpx;height:110rpx;border-radius:20rpx;background:#dfe9e3;display:grid;place-items:center;color:#315c4c}.item-main{flex:1;padding:0 22rpx}.name,.price{display:block}.name{font-weight:700}.price{color:#d64d37;margin-top:16rpx}.settle{position:fixed;left:0;right:0;bottom:100rpx;background:#fff;padding:24rpx 30rpx;display:flex;align-items:center;justify-content:space-between}.total{font-size:36rpx;font-weight:700;color:#d64d37;margin-left:16rpx}.settle button{margin:0;background:#123c2f;color:#fff;border-radius:30rpx;padding:0 46rpx}</style>
