<script setup lang="ts">
import { reactive, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { request } from '@/utils/request'
import type { Address } from '@/types'

const addresses=ref<Address[]>([]);const showForm=ref(false);const editingId=ref<string>();
const form=reactive({consignee:'',phone:'',province:'',city:'',district:'',detail:'',isDefault:false})
async function load(){addresses.value=await request<Address[]>({url:'/user/addresses',method:'GET'})}
function create(){editingId.value=undefined;Object.assign(form,{consignee:'',phone:'',province:'',city:'',district:'',detail:'',isDefault:addresses.value.length===0});showForm.value=true}
function edit(item:Address){editingId.value=item.id;Object.assign(form,{...item,isDefault:item.isDefault===1});showForm.value=true}
async function save(){if(!form.consignee||!/^1[3-9]\d{9}$/.test(form.phone)||!form.detail){uni.showToast({title:'请完整填写姓名、手机号和详细地址',icon:'none'});return}const url=editingId.value?`/user/addresses/${editingId.value}`:'/user/addresses';await request<Address>({url,method:editingId.value?'PUT':'POST',data:form});showForm.value=false;await load();uni.showToast({title:'保存成功'})}
async function setDefault(id:string){await request<void>({url:`/user/addresses/${id}/default`,method:'PUT'});await load()}
async function remove(id:string){uni.showModal({title:'删除地址',content:'确认删除该收货地址？',success:async result=>{if(result.confirm){await request<void>({url:`/user/addresses/${id}`,method:'DELETE'});await load()}}})}
function changeDefault(event: any){form.isDefault=Boolean(event.detail.value)}
onShow(load)
</script>
<template><view class="page"><view v-for="item in addresses" :key="item.id" class="card"><view class="top"><text class="person">{{item.consignee}}　{{item.phone}}</text><text v-if="item.isDefault" class="tag">默认</text></view><text class="address">{{item.province}}{{item.city}}{{item.district}}{{item.detail}}</text><view class="actions"><text @click="setDefault(item.id)">{{item.isDefault?'默认地址':'设为默认'}}</text><view><text @click="edit(item)">编辑</text><text class="danger" @click="remove(item.id)">删除</text></view></view></view><view v-if="!addresses.length" class="empty">还没有收货地址</view><button class="add" @click="create">+ 新增收货地址</button>
<view v-if="showForm" class="mask" @click.self="showForm=false"><view class="sheet"><text class="title">{{editingId?'编辑地址':'新增地址'}}</text><input v-model="form.consignee" placeholder="收货人姓名"/><input v-model="form.phone" type="number" maxlength="11" placeholder="手机号码"/><view class="region"><input v-model="form.province" placeholder="省"/><input v-model="form.city" placeholder="市"/><input v-model="form.district" placeholder="区"/></view><textarea v-model="form.detail" placeholder="街道、门牌号等详细地址"/><label class="default"><switch :checked="form.isDefault" color="#123c2f" @change="changeDefault"/>设为默认地址</label><button class="save" @click="save">保存地址</button></view></view></view></template>
<style scoped lang="scss">.page{padding:24rpx 24rpx 150rpx}.card{background:#fff;border-radius:24rpx;padding:28rpx;margin-bottom:20rpx}.top,.actions{display:flex;justify-content:space-between}.person{font-weight:700}.tag{background:#e4f2eb;color:#146c4b;padding:4rpx 12rpx;border-radius:12rpx;font-size:20rpx}.address{display:block;color:#58645e;margin:20rpx 0}.actions{border-top:1rpx solid #edf0ee;padding-top:20rpx;color:#718079;font-size:24rpx}.actions view text{margin-left:28rpx}.danger{color:#d64d37}.empty{text-align:center;color:#929a96;padding:200rpx 0}.add{position:fixed;left:30rpx;right:30rpx;bottom:40rpx;background:#123c2f;color:#fff;border-radius:30rpx}.mask{position:fixed;inset:0;background:rgba(0,0,0,.45);display:flex;align-items:flex-end;z-index:20}.sheet{width:100%;background:#fff;border-radius:34rpx 34rpx 0 0;padding:34rpx}.title{display:block;font-size:34rpx;font-weight:700;margin-bottom:24rpx}.sheet input,.sheet textarea{background:#f5f7f5;border-radius:16rpx;padding:22rpx;margin-bottom:16rpx}.sheet textarea{width:100%;box-sizing:border-box;height:130rpx}.region{display:flex;gap:12rpx}.region input{min-width:0;flex:1}.default{display:flex;align-items:center;gap:16rpx;margin:18rpx 0}.save{background:#123c2f;color:#fff;border-radius:28rpx}</style>
